server:
  port: 8083

spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: Post-Port-Service
          uri: lb://Post-Port-Service
          predicates:
            - Path=/api/posts/**

        - id: Comment-Port-Service
          uri: lb://Comment-Port-Service
          predicates:
            - Path=/api/comments/**


#-------------  Eureka Server configuration  -----------------
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
